-- Migration 001 — payment_links table
-- Tracks Tap payment link generation for each QuickBooks invoice.
-- Apply once: psql $DATABASE_URL -f db/migrations/001_create_payment_links.sql
-- For SQLite, this is handled automatically by db/payment_links.py on first run.

CREATE TABLE IF NOT EXISTS payment_links (
    id               TEXT        PRIMARY KEY,          -- UUID v4, generated by app
    invoice_id       TEXT        NOT NULL UNIQUE,      -- QBO invoice ID — idempotency anchor
    customer_id      TEXT        NOT NULL,             -- QBO customer ID
    tap_charge_id    TEXT        UNIQUE,               -- Tap charge ID returned after link creation
    payment_url      TEXT,                             -- The hosted checkout URL
    amount           REAL        NOT NULL,             -- Invoice amount
    currency         TEXT        NOT NULL DEFAULT 'KWD',
    status           TEXT        NOT NULL DEFAULT 'LINK_GENERATED',
    qbo_note_updated INTEGER     NOT NULL DEFAULT 0,   -- 1 once we wrote the link back to QBO
    qbo_note_updated_at TEXT,                         -- ISO-8601 timestamp of the QBO write
    created_at       TEXT        NOT NULL,             -- ISO-8601
    updated_at       TEXT        NOT NULL              -- ISO-8601
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pl_invoice_id  ON payment_links (invoice_id);
CREATE        INDEX IF NOT EXISTS idx_pl_charge_id   ON payment_links (tap_charge_id);
CREATE        INDEX IF NOT EXISTS idx_pl_status      ON payment_links (status);
